-- More seed cards

INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(40, 'Caterpie', 'Worm Pokémon', 'String Shot', '10', 'Fire', NULL, '1 Colorless', 45, 1, 3, 1),
(60, 'Metapod', 'Cocoon Pokémon', 'Stiffen', '0', 'Fire', NULL, '2 Colorless', 54, 1, 3, 2),
(80, 'Butterfree', 'Butterfly Pokémon', 'Whirlwind', '20', 'Fire', NULL, '1 Colorless', 33, 1, 3, 3),
(50, 'Weedle', 'Hairy Bug Pokémon', 'Poison Sting', '10', 'Fire', NULL, '1 Colorless', 69, 1, 3, 1),
(70, 'Kakuna', 'Cocoon Pokémon', 'Stiffen', '0', 'Fire', NULL, '2 Colorless', 33, 1, 3, 2),
(90, 'Beedrill', 'Poison Bee Pokémon', 'Twineedle', '30x', 'Fire', NULL, '2 Colorless', 17, 1, 3, 3),
(40, 'Oddish', 'Weed Pokémon', 'Absorb', '10', 'Fire', NULL, '1 Colorless', 58, 2, 3, 1),
(60, 'Gloom', 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', NULL, '2 Colorless', 32, 2, 3, 2),
(90, 'Vileplume', 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', NULL, '2 Colorless', 15, 2, 3, 3),
(50, 'Eevee', 'Evolution Pokémon', 'Tackle', '20', 'Fighting', NULL, '1 Colorless', 51, 2, 5, 1),
(70, 'Flareon', 'Flame Pokémon', 'Flamethrower', '60', 'Water', NULL, '2 Colorless', 12, 2, 1, 2),
(70, 'Vaporeon', 'Bubble Jet Pokémon', 'Water Gun', '30+', 'Electric', NULL, '2 Colorless', 28, 2, 2, 2),
(70, 'Jolteon', 'Lightning Pokémon', 'Pin Missile', '20x', 'Fighting', NULL, '1 Colorless', 20, 2, 4, 2),
(60, 'Cubone', 'Lonely Pokémon', 'Bone Attack', '20', 'Grass', NULL, '1 Colorless', 50, 3, 6, 1),
(80, 'Marowak', 'Bone Keeper Pokémon', 'Bonemerang', '30x', 'Grass', NULL, '2 Colorless', 26, 3, 6, 2),
(60, 'Zubat', 'Bat Pokémon', 'Leech Life', '10', 'Electric', NULL, '1 Colorless', 57, 3, 3, 1),
(80, 'Golbat', 'Bat Pokémon', 'Wing Attack', '30', 'Electric', NULL, '2 Colorless', 25, 3, 3, 2),
(60, 'Geodude', 'Rock Pokémon', 'Tackle', '20', 'Grass', NULL, '1 Colorless', 46, 3, 6, 1),
(80, 'Graveler', 'Rock Pokémon', 'Rock Throw', '40', 'Grass', NULL, '2 Colorless', 37, 3, 6, 2),
(100, 'Golem', 'Megaton Pokémon', 'Selfdestruct', '100', 'Grass', NULL, '3 Colorless', 36, 3, 6, 3),
(50, 'Horsea', 'Dragon Pokémon', 'Smokescreen', '10', 'Electric', NULL, '1 Colorless', 19, 3, 2, 1),
(80, 'Seadra', 'Dragon Pokémon', 'Water Gun', '20+', 'Electric', NULL, '2 Colorless', 42, 3, 2, 2),
(120, 'Dragonite', 'Dragon Pokémon', 'Slam', '40x', 'Electric', NULL, '3 Colorless', 4, 3, 2, 3),
(60, 'Magnemite', 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', NULL, '1 Colorless', 62, 1, 4, 1),
(80, 'Magneton', 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', NULL, '2 Colorless', 9, 1, 4, 2),
(50, 'Abra', 'Psi Pokémon', 'Psyshock', '10', 'Psychic', NULL, '1 Colorless', 43, 1, 5, 1),
(80, 'Kadabra', 'Psi Pokémon', 'Recover', '30', 'Psychic', NULL, '2 Colorless', 32, 1, 5, 2),
(100, 'Alakazam', 'Psi Pokémon', 'Confuse Ray', '30', 'Psychic', NULL, '3 Colorless', 1, 1, 5, 3),
(60, 'Diglett', 'Mole Pokémon', 'Dig', '10', 'Grass', NULL, '1 Colorless', 47, 1, 6, 1),
(80, 'Dugtrio', 'Mole Pokémon', 'Earthquake', '70', 'Grass', NULL, '2 Colorless', 19, 1, 6, 2);
