-- More seed cards

INSERT INTO tbl_cards (hp, name, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id, type_id, stage_id) VALUES
(50, 'Poliwag', 'Tadpole Pokémon', 'Water Gun', '10+', 'Electric', NULL, '1 Colorless', 60, 1, 2, 1),
(80, 'Poliwhirl', 'Tadpole Pokémon', 'Amnesia', '20', 'Electric', NULL, '2 Colorless', 36, 1, 2, 2),
(100, 'Poliwrath', 'Tadpole Pokémon', 'Water Gun', '30+', 'Electric', NULL, '3 Colorless', 13, 1, 2, 3),
(40, 'Nidoran♀', 'Poison Pin Pokémon', 'Scratch', '10', 'Psychic', NULL, '1 Colorless', 55, 2, 3, 1),
(70, 'Nidorina', 'Poison Pin Pokémon', 'Double Kick', '30x', 'Psychic', NULL, '2 Colorless', 36, 2, 3, 2),
(100, 'Nidoqueen', 'Drill Pokémon', 'Mega Punch', '40', 'Psychic', NULL, '3 Colorless', 7, 2, 3, 3),
(40, 'Nidoran♂', 'Poison Pin Pokémon', 'Horn Attack', '10', 'Psychic', NULL, '1 Colorless', 56, 2, 3, 1),
(80, 'Nidorino', 'Poison Pin Pokémon', 'Horn Drill', '50', 'Psychic', NULL, '2 Colorless', 39, 2, 3, 2),
(120, 'Nidoking', 'Drill Pokémon', 'Thrash', '30+', 'Psychic', NULL, '3 Colorless', 11, 2, 3, 3),
(50, 'Pidgey', 'Tiny Bird Pokémon', 'Gust', '10', 'Electric', NULL, '1 Colorless', 57, 1, 5, 1),
(80, 'Pidgeotto', 'Bird Pokémon', 'Whirlwind', '20', 'Electric', NULL, '2 Colorless', 22, 1, 5, 2),
(120, 'Pidgeot', 'Bird Pokémon', 'Hurricane', '30', 'Electric', NULL, '2 Colorless', 8, 1, 5, 3),
(60, 'Rattata', 'Mouse Pokémon', 'Bite', '20', 'Fighting', NULL, '1 Colorless', 61, 1, 5, 1),
(80, 'Raticate', 'Rat Pokémon', 'Super Fang', '—', 'Fighting', NULL, '1 Colorless', 40, 1, 5, 2),
(50, 'Sandshrew', 'Mouse Pokémon', 'Scratch', '20', 'Water', NULL, '1 Colorless', 64, 1, 6, 1),
(80, 'Sandslash', 'Mouse Pokémon', 'Slash', '40', 'Water', NULL, '2 Colorless', 31, 1, 6, 2),
(60, 'Ekans', 'Snake Pokémon', 'Wrap', '10', 'Psychic', NULL, '1 Colorless', 69, 1, 3, 1),
(90, 'Arbok', 'Cobra Pokémon', 'Poison Fang', '20', 'Psychic', NULL, '2 Colorless', 31, 1, 3, 2),
(50, 'Clefairy', 'Fairy Pokémon', 'Sing', '—', 'Steel', 'Psychic', '1 Colorless', 5, 1, 5, 1),
(90, 'Clefable', 'Fairy Pokémon', 'Metronome', '—', 'Steel', 'Psychic', '2 Colorless', 36, 1, 5, 2),
(60, 'Vulpix', 'Fox Pokémon', 'Confuse Ray', '10', 'Water', NULL, '1 Colorless', 68, 1, 1, 1),
(100, 'Ninetales', 'Fox Pokémon', 'Fire Blast', '80', 'Water', NULL, '2 Colorless', 12, 1, 1, 2),
(50, 'Growlithe', 'Puppy Pokémon', 'Flare', '20', 'Water', NULL, '1 Colorless', 28, 1, 1, 1),
(90, 'Arcanine', 'Legendary Pokémon', 'Flamethrower', '50', 'Water', NULL, '2 Colorless', 23, 1, 1, 2),
(60, 'Psyduck', 'Duck Pokémon', 'Headache', '—', 'Electric', NULL, '1 Colorless', 53, 3, 2, 1),
(80, 'Golduck', 'Duck Pokémon', 'Hyper Beam', '20', 'Electric', NULL, '2 Colorless', 25, 3, 2, 2),
(50, 'Tentacool', 'Jellyfish Pokémon', 'Acid', '10', 'Electric', NULL, '1 Colorless', 62, 3, 2, 1),
(80, 'Tentacruel', 'Jellyfish Pokémon', 'Supersonic', '—', 'Electric', NULL, '2 Colorless', 43, 3, 2, 2),
(60, 'Krabby', 'River Crab Pokémon', 'Vice Grip', '10', 'Electric', NULL, '1 Colorless', 51, 3, 2, 1),
(90, 'Kingler', 'Pincer Pokémon', 'Crabhammer', '40', 'Electric', NULL, '2 Colorless', 34, 3, 2, 2);
